### ISSUE TITLE
Helm chart deployment failure

### ISSUE THREAD

**Issue by peembe** [vbouchaud/k8s-ldap-auth#157]
Hi

```
% helm search repo vbouchaud
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION                                       
vbouchaud/k8s-ldap-auth	0.1.3        	v4.0.0     	Kubernetes webhook token authentication plugin ...
```

When I tried to deploy helm chart pod startup was failing with this error:

``` 
Warning  Failed     7m56s (x4 over 8m42s)   kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```

I had to change container specification in deployment configuration to
```
      containers:
      - args:
        - serve
```

**Comment by vbouchaud** [comment]
Hi @peembe,

Thanks for reporting that. It probably came from some changes I made when I switched to a distroless image. I'll have a look at it.

**Comment by vbouchaud** [comment]
It was indeed a bug I introduced when switching to a distroless image in 9fb47104304d5d7883c5e1ec658ff80e3c11d534. `k8s-ldap-auth` binary went from `/usr/bin/` to `/` (out of `$PATH`) and since the entrypoint is only `/k8s-ldap-auth`, the chart should indeed use `serve` as the only argument.
